[[redirects]]
  from = "/api/*"
  to = "https://recrutement-m56g04i0w-benissa1.vercel.app/api/:splat"
  host = "recrutement-m56g04i0w-benissa1.vercel.app"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200